# Generated by Django 4.2.5 on 2023-09-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0003_problem_userprofile_delete_employee_delete_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
